### ISSUE TITLE
Outland and Draenor

### ISSUE THREAD

**Issue by Resike** [keyboardturner/WoWMapUprez#9]
**Zone Name**
Draenor

**Screenshots**
Vertical missalignment on the world map
![image](https://user-images.githubusercontent.com/3955703/112567177-ab3ca080-8de0-11eb-938a-14623ef22e5d.png)
Vertical and horizontal missalignment on the world map
![image](https://user-images.githubusercontent.com/3955703/112567309-e8a12e00-8de0-11eb-85ab-38b7fdf2b1f5.png)

**Zone Name**
Nagrand (Draenor)

**Screenshots**
Vertical and horizontal missalignment
![image](https://user-images.githubusercontent.com/3955703/112566462-52b8d380-8ddf-11eb-85a7-e951b62d3caf.png)

**Zone Name**
Ashran (Draenor)

**Screenshots**
Missing panel
![image](https://user-images.githubusercontent.com/3955703/112566532-75e38300-8ddf-11eb-8a6b-485314f167df.png)
Vertical and horizontal missalignment
![image](https://user-images.githubusercontent.com/3955703/112566603-99a6c900-8ddf-11eb-87aa-7fc438a18ddc.png)

**Zone Name**
Hellfire Penninsula (Outland)

**Screenshots**
Vertical missalignment
![image](https://user-images.githubusercontent.com/3955703/112566687-be02a580-8ddf-11eb-8e9c-731038f12360.png)

**Zone Name**
Shattrath (Outland)

**Screenshots**
Fixing text
![image](https://user-images.githubusercontent.com/3955703/112568389-ad9ffa00-8de2-11eb-824f-b22990fc154e.png)
Vertical and horizontal missalignment
![image](https://user-images.githubusercontent.com/3955703/112566810-f73b1580-8ddf-11eb-8d8e-72b41c546506.png)
Vertical and horizontal missalignment
![image](https://user-images.githubusercontent.com/3955703/112566866-0de16c80-8de0-11eb-8611-a9426359627e.png)
Vertical and horizontal missalignment
![image](https://user-images.githubusercontent.com/3955703/112566924-2487c380-8de0-11eb-99ba-1c3bbacf06b3.png)
Vertical and horizontal missalignment
![image](https://user-images.githubusercontent.com/3955703/112566970-3d907480-8de0-11eb-8207-670e005d9212.png)

**Zone Name**
Blade's Edge Mountains (Outland)

**Screenshots**
Vertical missalignment
![image](https://user-images.githubusercontent.com/3955703/112567040-67499b80-8de0-11eb-9505-647cb40c8cd5.png)

**Comment by keyboardturner** [comment]
hi all these places should now be fixed - I think the Highmaul location was already fixed in my previous update actually

**Comment by Resike** [comment]
Stormshield and Warspear still have these issues:
![image](https://user-images.githubusercontent.com/3955703/113463461-0ba59080-9426-11eb-8bcc-9b8dba5289e4.png)
![image](https://user-images.githubusercontent.com/3955703/113463464-195b1600-9426-11eb-95d7-fc65ff2411ac.png)

And this is in Zangarmarsh:
![image](https://user-images.githubusercontent.com/3955703/113463548-96868b00-9426-11eb-97ca-f15c8497d5f8.png)

Talador:
![image](https://user-images.githubusercontent.com/3955703/113463603-13b20000-9427-11eb-8e33-19a32b15bd2c.png)
